version: '3'

services:
  nginx:
    build: ./nginx
    image: nginx:seatdev
    restart: always
    privileged: true  # Neccessary for now. Find a way to not do this!
    env_file:
      - .env
    volumes:
      - pathfinder-public:/var/www/pathfinder:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf.template:ro
      - ./config/nginx/conf.d:/etc/nginx/conf.d/templates:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - pathfinder-php
    ports:
      - 80:80
      - 443:443
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  mariadb:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./config/sql:/docker-entrypoint-initdb.d
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  redis:
    image: redis:5-alpine
    restart: always
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  pathfinder-php:
    build:
      context: ./pathfinder
      args:
        - VERSION=master
    image: pathfinder:seatdev
    command: php-fpm7.2 -F
    depends_on:
      - mariadb
      - redis
    volumes:
      - pathfinder-public:/var/www/pathfinder
      - ./config/config.ini:/var/www/pathfinder/app/config.ini:ro
      - ./config/environment.ini:/var/www/pathfinder/app/environment.ini:ro
      - ./config/pathfinder.ini:/var/www/pathfinder/app/pathfinder.ini:ro
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  seat-web:
    image: eveseat/seat:4
    restart: always
    command: web
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
                
  seat-worker:
    image: eveseat/seat:4
    restart: always
    command: worker
    env_file:
      - .env
    depends_on:
      - seat-web # so that we can get db migrations done
      - mariadb
      - redis
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  seat-cron:
    image: eveseat/seat:4
    restart: always
    command: cron
    env_file:
      - .env
    depends_on:
      - seat-web # so that we can get db migrations done
      - mariadb
      - redis
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

volumes:
  pathfinder-public:
  mariadb-data:

networks:
  seat-network:
